### ISSUE TITLE
Support Heroku deployments

### ISSUE THREAD

**Issue by derek-watson** [feathersjs/feathers-cli#1]
Migrated from feathersjs/feathers#250:

We also have some thoughts around being able to do `feathers deploy` or `feathers deploy:heroku` and it will deploy your app.

We can start small and just support Heroku but we might want to wrap [Otto](https://www.ottoproject.io/) in the future in order to support easy dev and prod deployments.

**Comment by ekryski** [comment]
We had discussed in Slack that the first order of business will be trying to be able to deploy to Heroku and then we'll see what we learn from that.

**Comment by ekryski** [comment]
@derek-watson and I had a google hangout the other day. We talked about using the heroku tool belt but using the API with some sort of `.feathers` file that stores your credentials would be better because you can't easily install the tool belt programatically.

The other thought was to have a `feathers.json` that has your development and production config so that we can use that to determine what and where to deploy.

**Comment by startupthekid** [comment]
I don't know how useful a Heroku specific deployment tool would be since you can authenticate Heroku to automatically deploy whenever pushed to a particular branch (default `master`). I could see the value however in a generic deployment tool with sub plugins which could support anything from AWS EC2 to Heroku to Docker based deployments.

Of course having a tool that allows me to run `feathers deploy` without ever having configure anything in Heroku would be amazing. Not sure how feasible that is. I'd be glad to contribute to the ongoing discussion (can't commit dev time but glad to chat about different directions). Maybe this could even be a separate cli tool (`feathers-deploy`)?

**Comment by ekryski** [comment]
After some experimentation we're not going to tackle this. It's pretty simple to do yourself as it's like any other Express app. You can simply refer to this guide https://devcenter.heroku.com/articles/deploying-nodejs.

**Comment by PanMan** [comment]
See https://github.com/feathersjs/feathers-docs/issues/66 for how to set the right Port
