### ISSUE TITLE
Generate a directory for the app

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-cli#10]
It's a pet peeve of mine that I have to create and `cd` into a directory in order to run yeoman. We should do that for people. Less keystrokes FTW!!

**Comment by derek-watson** [comment]
@ekryski what do you think the behaviour should look like? 

I'm wondering if the `generate` command should take a directory name as an argument eg.

```
feathers generate my-app-name
```

which would warn about overwrites if `./my-app-name` exists, and otherwise create the directory and generate into it. If no argument is passed, it would prompt for an app name and use that going forward.

**Comment by ekryski** [comment]
@derek-watson :+1: the only thing with that syntax is won't it conflict with the other generators? Could you potentially have name clashes if someone wanted to call their app `service` or something?

If so, maybe we can just do a `--name my-app` flag instead?

**Comment by derek-watson** [comment]
Right, I meant to say `feathers generate app my-app`, but `--name` works too.

**Comment by ekryski** [comment]
nope I like `feathers generate app my-app` better. It's more explicit. `feathers generate` doesn't really tell you what you will generate.

**Comment by derek-watson** [comment]
Ok, great, current `feathers generate` is a shortcut for `feathers generate app`, so maybe just remove that for clarity?

**Comment by ekryski** [comment]
totally

**Comment by ekryski** [comment]
Fixed in 2.0
