### ISSUE TITLE
Removing services with the CLI

### ISSUE THREAD

**Issue by jmarlow4** [feathersjs/feathers-cli#45]
I was wondering if this feature was already implemented. I can't find anything online about it. If so, what's the command? If there is no command, what would be the safest way to remove a service?

**Comment by daffl** [comment]
There is not a lot of magic to how services are registered. To remove a generated service you can delete the `src/services/<servicename>` and `test/services/<servicename>` folders and then update `src/services/index.js` taking out the `require` and `app.configure` statement for that service.

**Comment by emeagenciadigital** [comment]
it will be nice to have a CLI way of doing it.

**Comment by marshallswain** [comment]
@emeagenciadigital the core team will not be working on this feature, but we are open to tested PRs.  ;)

**Comment by VanMen** [comment]
CMIIW, I think we also have to delete /src/model/<servicename>.model.js

**Comment by SaabirMohamed** [comment]
due to lazyness ... 
for now , I just do this with a script  (pass the name of the service as the argument)
_________________________
#!/bin/bash
cat src/services/index.js | grep -v "$1" > src/services/index.js  [removes the service from index]
rm -rf src/services/$1
rm -rf src/models/$1
________________________

I put the above 3 lines in a bash script and run ./removeService service-I-spelt-wrong [enter]
