### ISSUE TITLE
One-file-per-service

### ISSUE THREAD

**Issue by hubgit** [feathersjs/feathers-cli#76]
Having seen the simplicity of [Next.js' one-file-per-page](https://zeit.co/blog/next#zero-setup.-use-the-filesystem-as-an-api), where each JS file in the `pages` folder maps to a top-level route that renders a React component, I've been thinking that one-file-per-service (where each JS file in the `services` folder maps to a top-level service) might make Feathers easier to get started with.

For example, instead of having these files for a generated service:

```js
// app.js
const services = require('./services');
app.configure(services);

// services/index.js
'use strict';

const articles = require('./articles/articles.service.js');

module.exports = function() {
  const app = this; // eslint-disable-line no-unused-vars
  app.configure(articles);
};

// services/articles/articles.filters.js
/*eslint no-console: 1 */
console.warn('You are using the default filter for the articles service. For more information about event filters see https://docs.feathersjs.com/api/events.html#event-filtering'); // eslint-disable-line no-console

module.exports = function(data, connection, hook) { // eslint-disable-line no-unused-vars
  return data;
};

// services/articles/articles.hooks.js
'use strict';

module.exports = {
  before: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },
  after: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  },
  error: {
    all: [],
    find: [],
    get: [],
    create: [],
    update: [],
    patch: [],
    remove: []
  }
};

// services/articles/articles.service.js
'use strict';

// Initializes the `articles` service on path `/articles`
const createService = require('feathers-mongoose');
const createModel = require('../../models/articles.model');
const hooks = require('./articles.hooks');
const filters = require('./articles.filters');

module.exports = function() {
  const app = this;
  const Model = createModel(app);
  const paginate = app.get('paginate');

  const options = {
    name: 'articles',
    Model,
    paginate
  };

  // Initialize our service with any options it requires
  app.use('/articles', createService(options));

  // Get our initialized service so that we can register hooks and filters
  const service = app.service('articles');

  service.hooks(hooks);

  if (service.filter) {
    service.filter(filters);
  }
};

// models/articles.model.js
'use strict';

// articles-model.js - A mongoose model
// 
// See http://mongoosejs.com/docs/models.html
// for more of what you can do here.
module.exports = function(app) {
  const mongooseClient = app.get('mongooseClient');
  const articles = new mongooseClient.Schema({
    text: { type: String, required: true },
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
  });

  return mongooseClient.model('articles', articles);
};
```

there would just be this:

```js
// app.js
const glob = require('glob');
glob.sync('./services/*.js', { cwd: __dirname }).map(require).forEach(app.configure.bind(app));

// services/articles.js
'use strict';

const mongooseService = require('feathers-mongoose');

module.exports = function () {
  const app = this;

  const mongoose = app.get('mongooseClient');

  const schema = {
    text: { type: String, required: true },
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
  };

  const hooks = {
    before: {
      all: [],
      find: [],
      get: [],
      create: [],
      update: [],
      patch: [],
      remove: []
    },

    after: {
      all: [],
      find: [],
      get: [],
      create: [],
      update: [],
      patch: [],
      remove: []
    },

    error: {
      all: [],
      find: [],
      get: [],
      create: [],
      update: [],
      patch: [],
      remove: []
    }
  };

  const filter = function (data, connection, hook) { // eslint-disable-line no-unused-vars
    return data;
  };

  app.use('/articles', mongooseService({
    name: 'articles',
    Model: mongoose.model('articles', new mongoose.Schema(schema)),
    paginate: app.get('paginate')
  }));

  app.service('articles').hooks(hooks).filter(filter);
};
```

It's exactly the same information, just organised differently (and still in a way that it's straightforward to move the hooks, schema or filter out to a separate file later if they get too large).

**Comment by marshallswain** [comment]
Why do you feel this makes it easier to get started?  I definitely prefer keeping them in separate files.  For almost every service I've ever made I've had to split into multiple files because they get long.  I feel like the current layout is much better than the one we just left behind.   The easiest way to get a single file is to simply delete everything but the main entry file for each service, which isn't a complicated process at all.  I think the current system is a nice balance.

**Comment by hubgit** [comment]
I feel this is appealing for the same reason that Next.js' layout is appealing: to create a new service you just need to add a single file, and everything the service needs is in there.

**Comment by marshallswain** [comment]
I do like the idea of making it more lightweight (featherweight?).  I can see how it would be less daunting for a newcomer, too.  We just have a lot of other efforts in the works, so I'm going to close this, but we will happily consider a pull request against the generator-feathers repo.

**Comment by eddyystop** [comment]
This feels like convention vs configuration. My feeling about this topic is
that you have to carefully decide how much "magic" you want.

Sails is extremely convention driven. Its conventions take a while to
learn, but that's better than yourself writing the distressing amount of
boilerplate required to stitch the magic together.

Next's conventions are needed, I feel, because Next does both server and
client-side magic. There's not that much to do to stitch React components
together, but enough to be annoying. Then you have to do it server-side as
well.

Feathers is much more lightweight that either Sails or Next. Convention
would save a small amount of code.

The cost would be to explain the additional "magic" Feathers would then
contain, and I don't think that's less effort than explaining how to stitch
things together. You can look at the Auk doc's Basic Feathers guide to see
how simple it is to explain the stitching.

My personal feeling is that, unless there are significant benefits, "magic"
should be avoided. I'm a muggle.

On Fri, Mar 31, 2017 at 4:09 PM, Marshall Thompson <notifications@github.com

**Comment by eddyystop** [comment]
This feels like convention vs configuration. My feeling about this topic is that you have to carefully decide how much "magic" you want.

Sails is extremely convention driven. Its conventions take a while to learn, but that's better than yourself writing the distressing amount of boilerplate required to stitch the magic together.

Next's conventions are needed, I feel, because Next does both server and client-side magic. There's not that much to do to stitch React components together, but enough to be annoying. Then you have to do it server-side as well.

Feathers is much more lightweight that either Sails or Next. Convention would save a small amount of code.

The cost would be to explain the additional "magic" Feathers would then contain, and I don't think that's less effort than explaining how to stitch things together. You can look at the Auk doc's Basic Feathers guide to see how simple it is to explain the stitching.

My personal feeling is that, unless there are significant benefits, "magic" should be avoided. I'm a muggle
