### ISSUE TITLE
Whitespace handling

### ISSUE THREAD

**Issue by christopherjbaker** [feathersjs/feathers-cli#92]
At present, all the generated code uses spaces. I would like if the generator had a flag to switch to tabs (or autodetected from index.js), but at the very least, it would be nice if the generator auto-detected when it was modifying files (such as tests, services/index.js, etc) so that the added lines matched the file they were being added to.

**Comment by daffl** [comment]
The easiest way right now would probably be to change the whitespace setting in the `.eslintrc.json` and then run it with `--fix` which should update all files accordingly.

I'd like to avoid adding a new prompt for every style choice that could potentially be made. What I'd recommend to customize the generator is to fork it, make the changes, publish it into your own namespace and then use it just like any other [Yeoman](http://yeoman.io/) generator. We do always take pull requests with improvement suggestions of course.

**Comment by daffl** [comment]
Thanks again for the suggestion. Our goal with the generator is to pick sane defaults and keep the number of prompts as low as possible, especially when it is not relevant to other generators. Every new prompt will have to be implemented, tested, documented and released and also requires all tutorials  that are showing and/or explaining the prompts (including screenshots) to be updated so we do have to carefully any new options we are going to add.

Since I think there is a fairly straightforward workaround I am going to close this issue.

**Comment by christopherjbaker** [comment]
Sorry I didn't reply sooner, I was in Chicago all week. Totally understand why you wouldn't want to add a new prompt/option.
